export enum STATE {
  OPENED = 'OPENED',
  TO_DO = 'TO DO',
  ACCEPTED = 'ACCEPTED',
  REFUSED = 'REFUSED',
  VALID = 'VALID',
  IN_PROGRESS = 'IN_PROGRESS',
  REQUEST = 'REQUEST',
  SUSPENDED = 'SUSPENDED',
  TREATED = 'TREATED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
  PENDING = 'PENDING',
  EXIST = 'EXIST',
  REJECTED = 'REJECTED',
  DELETED = 'DELETED',
}

export enum TYPE_APPOINTMENT {
  PUNCTUAL = 'PUNCTUAL',
  REGULAR = 'REGULAR',
}

export enum TYPE_CHALLENGE {
  INTERNE = 'INTERNE',
  EXTERNE = 'EXTERNE',
  ARCHIVED = 'ARCHIVED',
}

export enum TYPE_TASKS {
  INTERNE = 'INTERNE',
  PROCESS = 'PROCESS',
  OBJECTIVE = 'OBJECTIVE',
}

export enum TYPE_FREQUENCE {
  JOURNALIER = 'JOURNALIER',
  HEBDOMADAIRE = 'HEBDOMADAIRE',
  MENSUEL = 'MENSUEL',
  TRIMESTRIEL = 'TRIMESTRIEL',
  SEMESTRIEL = 'SEMESTRIEL',
  ANNUELLE = 'ANNUELLE',
}

export enum TYPE_SOURCE_TASK {
  INCIDENT = 'INCIDENT',
  TASK = 'TASK',
  CLAIM = 'CLAIM',
  SUGGESTION = 'SUGGESTION',
}

export enum TYPE_USERS {
  QUALITY = 'QUALITY',
  INCIDENT = 'INCIDENT',
  TOP_MANAGER = 'TOP_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'TEAM_CHIEF',
}
export enum STATUS_USERS {
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE',
}

export enum LEVEL_ROLE {
  EMPLOYEE = 1,
  SUPERVISOR = 2,
  MANAGER = 3,
  TOP_MANAGER = 4,
}
export enum TYPE_AUTHORIZE {
  LEVEL_CHEF = 'LEVEL_CHEF',
}

export enum TYPE_DEPARTMENT {
  INFORMATION_TECHNOLOGY = 1,
  INCIDENT = 2,
  QUALITY = 3,
  ALL = 0,
}

export enum TYPE_TARGET {
  NUMBER = 'NUMBER',
  PERCENT = 'PERCENT',
  COST = 'COST',
  TIME = 'TIME',
}

export enum TYPE_KPI {
  PROCESS = 'PROCESS',
  OBJECTIVE = 'OBJECTIVE',
}

export enum FORMAT_DATE {
  DATE = 'dd/MM/yyyy',
  DATETIME = 'dd/MM/yyyy hh:ss',
}

export enum TYPE_LIST {
  VALIDATION = 'VALIDATION',
  ASSIGNER = 'ASSIGNER',
}
export enum INFLUENCE {
  HIGH = 'HIGH',
  MIDDLE = 'MIDDLE',
  LOW = 'LOW',
}

export enum IMPACT {
  ARRET_TOTAL = 'ARRET_TOTAL',
}

export enum GROUP {
  PARTNER = 'PARTNER',
  SUPPLIER = 'SUPPLIER',
  SHAREHOLDER = 'SHAREHOLDER',
  CUSTOMER = 'CUSTOMER',
 // ARCHIVED = 'ARCHIVED',

}

export enum SUB_GROUP {
  STATE_STRUCTURE = 'STATE STRUCTURE',
  PUBLIC_INSTITUTIONS = 'PUBLIC INSTITUTIONS',
  TRADE_UNION_AND_CONSULAR_CHAMBER = 'TRADE_UNION AND CONSULAR CHAMBER',
  BANKS_AND_MICROFINANCE = 'BANKS AND MICROFINANCE',
  UNIVERSITIES_AND_RESEACH_CENTER = 'UNIVERSITIES AND RESEACH CENTER',
  DONORS_AND_COOPERATION = 'DONORS AND COOPERATION',
  PRIVATE_COMPANIES = 'PRIVATE COMPANIES',
}

export enum STATE_STRUCTURE {
  MINISTRY = 'MINISTRY',
  REGIONAL_DELEGATION = 'REGIONAL DELEGATION',
}

export enum TRADE_UNION_AND_CONSULAR_CHAMBER {
  TRADE_UNION = 'TRADE UNION',
  CONSULAR_CHAMBER = 'CONSULAR CHAMBER',
}

export enum BANKS_AND_MICROFINANCE {
  BANKS = 'BANKS',
  MICROFINANCE = 'MICROFINANCE',
}

export enum UNIVERSITIES_AND_RESEACH_CENTER {
  PUBLIC_UNIVERSITIES = 'PUBLIC UNIVERSITIES',
  PRIVATE_UNIVERSITIES = 'PRIVATE UNIVERSITIES',
  TRAINING_SCHOOLS = 'TRAINING SCHOOLS',
  RESEACH_CENTER = 'RESEACH CENTER',
}

export enum DONORS_AND_COOPERATION {
  DONORS = 'DONORS',
  COOPERATION = 'COOPERATION',
}

export enum PRIVATE_COMPANIES {
  PRIMARY_SECTOR = 'PRIMARY_SECTOR',
  SECONDARY_SECTOR = 'SECONDARY_SECTOR',
  TERTIARY_SECTOR = 'TERTIARY_SECTOR',
}
export enum TABLE_REF {
  INCIDENTS = 'incidents',
  CLAIMS = 'claims',
  SUGGESTIONS = 'suggestions',
}
export enum TYPE_DOC {
  FOLDER = 'FOLDER',
  FILE = 'FILE',
  PRIMARY_SECTOR = 'PRIMARY SECTOR',
  SECONDARY_SECTOR = 'SECONDARY SECTOR',
  TERTIARY_SECTOR = 'TERTIARY SECTOR',
}

export enum SUB_GROUP_SHAREHOLDER {
  SHARE = 'SHARE',
  EMPLOYEE = 'EMPLOYEE',}

export enum TYPE_REP {
  LEGALE = 'LEGALE',
  REGLEMENTAIRE = 'REGLEMENTAIRE',
  CLIENT = 'CLIENT',
  INTERNE = 'INTERNE',
}

export enum TYPE_SOURCE {
  INTERNE = 'INTERNE',
  EXTERNE = 'EXTERNE',
}

export enum TYPE_NORME {
  NORME_PRODUIT = 'NORME PRODUIT',
  NORME_SERVICE = 'NORME SERVICE',
  NORME_PRESCRIPTIVE = 'NORME PRESCRIPTIVE',
  NORME_MANAGEMENT = 'NORME MANAGEMENT',
}
export enum TYPE_LOCALISATION {
  INTERNATIONALE = 'INTERNATIONALE',
  NATIONALE = 'NATIONALE',
}

// ENUMERATION  DANGER : * CLASSES DANGER
export enum TYPE_DANGER {
   DANGER_MECA_ET_PHY = 'DANGER MECA ET PHY',
   DANGER_ELECTRIQUE = 'DANGER ELECTRIQUE',
   SUBSTANCE_DANGEREUSE = 'SUBSTANCE DANGEREUSE',
   DANGER_BIOLOIQUE = 'DANGER BIOLOIQUE',
   DANGER_CHIMIQUE = 'DANGER CHIMIQUE',
   DANGER_THERMIQUE = 'DANGER THERMIQUE',
   DANGER_INCENDIE_ET_EXPLOSION = 'DANGER INCENDIE ET EXPLOSION',
   DANGER_PROCEDURAL = 'DANGER PROCEDURAL',
   DANGER_PSYCHOLOGIQUE = 'DANGER PSYCHOLOGIQUE',
   DANGER_ENVIRONNEMENT_TRAVAIL = 'DANGER ENVIRONNEMENT TRAVAIL',
   DANGER_FACTEUR_HUMAIN = 'DANGER_FACTEUR HUMAIN',
   DANGER_AGENT_PHYSIQUE_SPECIFIQUES = 'DANGER AGENT PHYSIQUE SPECIFIQUES',
   DANGER_CYBERCRIMINALITE = 'DANGER CYBERCRIMINALITE',
   DANGER_ENVIRONNEMENT = 'DANGER ENVIRONNEMENT',
  }

export enum DANGER_MECA_ET_PHY {
  UTILISATION_DANGEREUSE = 'UTILISATION DANGEREUSE',
  MATIERE_DANGEREUSE = 'MATIERE DANGEREUSE',
  MOUVEMENT_DANGEREUX = 'MOUVEMENT DANGEREUX',
  POSITION_DANGEREUSE = 'POSITION DANGEREUSE',
  SURFACE_DANGEREUSE = 'SURFACE DANGEREUSE',
}
export enum DANGER_ELECTRIQUE {
  CONTACT_DIRECT = 'CONTACT DIRECT',
  CONTACT_INDIRECT = 'CONTACT INDIRECTE',
  REGIME_DE_TENSION = 'REGIME DE TENSION',
  SURINTENSITE = 'SURINTENSITE',
  TENSION_ET_CLASSE = 'TENSION ET CLASSE',
  TYPE_DE_COURANT = 'TYPE DE COURANT',
}
export enum SUBSTANCE_DANGEREUSE {
  AEROSOL = 'AEROSOL',
  GAZ = 'GAZ',
  LIQUIDE = 'LIQUIDE',
  MELANGE = 'MELANGE',
  PEROYDE = 'PEROYDE ORGANIQUE',
  SOLIDE = 'SOLIDE',
}
export enum DANGER_BIOLOIQUE {
  BACTERIE = 'BACTERIE',
  OGM = 'OGM',
  PARASITE = 'PARASITE',
  TOXINES = 'TOXINES',
  VIRUS = 'VIRUS',
}
export enum DANGER_CHIMIQUE {
  ALLIAGE = 'ALLIAGE',
  COMPOSE_CHI = 'COMPOSE CHIMIQUE',
  COMPOSE_ORG = 'COMPOSE ORGANIQUE',
}
export enum DANGER_THERMIQUE {
  COONTACT_CHAUD = 'CONTACT CHAUD',
  COONTACT_FROID = 'CONTACT FROID',
}
export enum DANGER_INCENDIE_ET_EXPLOSION {
  MATIERE_SOLIDE_INFLAMMABLE = 'MATIERE SOLIDE INFLAMMABLE',
  MATIERE_LIQUIDE_INFLAMMABLE = 'MATIERE LIQUIDE INFLAMMABLE',
  MATIERE_GAZEUX_INFLAMMABLE = 'MATIERE GAZEUX INFLAMMABLE',
  ATMOSPHERE_EXPLOSIVE = 'ATMOSPHERE EXPLOSIVE',
  SUBSTANCE_EXPLOSIVE = 'SUBSTANCE EXPLOSIVE',
}
export enum DANGER_PROCEDURAL {
  PROCESSUS_MANAGEMENT = 'DANGER LIES AUX PROCESSUS MANAGEMENT',
  PROCESSUS_REALISATION = 'DANGER LIES AUX PROCESSUS REALISATION',
  PROCESSUS_SUPPORT = 'DANGER LIES AUX PROCESSUS SUPPORT',
}
export enum DANGER_PSYCHOLOGIQUE {
  PSYCHOLOGIE_NEGATIVE = 'PRESSION PSYCHOLOGIE_NEGATIVE',
  PSYCHOLOGIE_POSITIVE = 'PRESSION PSYCHOLOGIE_POSITIVE',
  PSYCHOLOGIE_INTERIEURE = 'PRESSION PSYCHOLOGIE_INTERIEURE',
  PSYCHOLOGIE_EXTERIEURE = 'PRESSION PSYCHOLOGIE_EXTERIEURE',
}
export enum DANGER_ENVIRONNEMENT_TRAVAIL {
  CLIMAT = 'CLIMAT',
  LUMINOSITE = 'LUMINOSITE DU LIEU',
  ESPACE = 'ESPACE NECESSAIRE',
  VOIE = 'VOIE DE CIRCULATION',
}
export enum DANGER_FACTEUR_HUMAIN {
  VOLONTAIRE = 'ACTION VOLONTAIRE',
  INVOLONTAIRE = 'ACTION INVOLONTAIRE',
}
export enum DANGER_AGENT_PHYSIQUE_SPECIFIQUES {
  NUISANCES_SONORES = 'NUISANCES SONORES',
  ULTRASONS = 'ULTRASONS',
  INFRASONS = 'INFRASONS',
  VIBRATIONS_CORPS_ENTIER = 'VIBRATIONS CORPS ENTIER',
  VIBRATIONS_MAIN_BRAS = 'VIBRATIONS MAIN BRAS',
  RAYONNEMENT_NON_IONISANT = 'RAYONNEMENT NON IONISANT',
  RAYONNEMENT_IONISANT = 'RAYONNEMENT IONISANT',
  CHAMP_ELECTROMAGNETIQUE = 'CHAMP ELECTROMAGNETIQUE',
  TRAVAIL = 'TRAVAIL EN DEPRESSION OU EN SUPPRESSION',
}
export enum DANGER_CYBERCRIMINALITE {
  DANGER_CYBERCRIMINALITE = 'DANGER LIEE A LA CYBERCRIMINALITE',
}
export enum DANGER_ENVIRONNEMENT {
  DANGER_ENVIRONNEMENT = 'DANGER LIEE A LA ENVIRONNEMENT',
}


// * CATEGORIE DANGER
// REGIME TENSION
 export enum REGIME_DE_TENSION {
  TENSION_HAUTE = 'TENSION HAUTE',
  TENSION_BASSE = 'TENSION BASSE',
 }
 // TYPE COURANT
 export enum TYPE_DE_COURANT {
  COURANT_CONTINU = 'COURANT CONTINU',
  COURANT_ALTERNATIF = 'COURANT ALTERNATIF',
 }
 //GAZ
 export enum GAZ {
  GAZ_NATUREL = 'GAZ NATUREL',
  GAZ_INFLAMMABLE = 'GAZ INFLAMMABLE',
  GAZ_COMBURANT = 'GAZ COMBURANT',
  GAZ_SOUS_PRESSION = 'GAZ SOUS PRESSION',
  GAZ_DERIVE_DE_PETROLE = 'GAZ DERIVE DE PETROLE',
  BIOGAZ = 'BIOGAZ',
  GAZ_LIQUEFIE = 'GAZ LIQUEFIE',
  GAZ_CHIMIQUE = 'GAZ CHIMIQUE',
 }
 //TRAVAIL
 export enum TRAVAIL {
  TRAVAIL_DEPRESSION = 'TRAVAIL EN DEPRESSION',
  TRAVAIL_SUPRESSION = 'TRAVAIL EN SUPRESSION',
 }
export enum TYPE_AUDITEUR {
  INTERNE = 'INTERNE',
  EXTERNE = 'EXTERNE',
}

export enum CATEGORIE_AUDITEUR {
  AUDITEUR = 'AUDITEUR',
  LEAD_AUDITEUR = 'LEAD AUDITEUR',
  TRAINEE = 'TRAINEE',
}


export enum TYPE_AUDIT {
  INTERNE = 'INTERNE',
  EXTERNE = 'EXTERNE',
}

export enum CATEGORIE_AUDIT {
  DOCUMENTAIRE = 'DOCUMENTAIRE',
  PRODUIT = 'PRODUIT',
  PROCESSUS = 'PROCESSUS',
  SYSTEME = 'SYSTEME',
}

export enum PERIODE_AUDIT {
  JANVIER = 'JANVIER',
  FEVRIER = 'FEVRIER',
  MARS = 'MARS',
  AVRIL = 'AVRIL',
  MAI = 'MAI',
  JUIN = 'JUIN',
  JUILLET = 'JUILLET',
  AOUT = 'AOUT',
  SEPTEMBRE = 'SEPTEMBRE',
  OCTOBRE = 'OCTOBRE',
  NOVEMBRE = 'NOVEMBRE',
  DECEMBRE = 'DECEMBRE',
}



